### ISSUE TITLE
Too much GPU usage

### ISSUE THREAD

**Issue by tungedng2710** [ruizhecao96/CMGAN#3]
I have run `evaluation.py` on your given AudioSamples with a RTX 2080Ti. However, I got an error: CUDA out of memory. I aslo tried to infer your model with a single file, but the GPU use approximately 8GB VRAM. I was confused by this situation because your generator has about 1.8M parameters only.

**Comment by ruizhecao96** [comment]
Sorry for the late reply. Due to the huge computational complexity of the Conformer, the model still needs large memory. For this problem, you can try to change the arguments 'cut_len' in the function 'enhance_one_track' in the evaluation to 8 seconds or 4 seconds.

**Comment by codddaw** [comment]
I have change the 'cut_len' to 4 seconds, but I got an error:  assert len(est_audio) == length
AssertionError, what should I do?

**Comment by ruizhecao96** [comment]
Sry for the late reply, can you show me in which line the error happened? I guess it is in the evaluation stage? If so just comment this line out because it ensures the ISTFT can produce the same length track as input. Due to the overlap problem sometimes it doesn't, but it will only be a little bit shorter compared to the input track.

> I have change the 'cut_len' to 4 seconds, but I got an error: assert len(est_audio) == length AssertionError, what should I do?

**Comment by codddaw** [comment]
> 

thanks a lot
